source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/m&i.conf
source = ~/.config/hypr/configs/look.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/basekeys.conf
source = ~/.config/hypr/configs/keybinds.conf
