bind = SUPER,       Return,    exec, kitty
bind = SUPER,       D,         exec, rofi -show drun
bind = SUPER, B,                exec, librewolf
#bind = SUPER,       B,         exec, zen-browser
#bind = SUPER,       B,         exec, brave
#bind = SUPER,       B,         exec, firefox
#bind = SUPER,       B,         exec, helium-browser
bind = SUPER,       M,         exec, spotify-launcher
bind = SUPER,       N,         exec, obsidian
bind = SUPER,       E,         exec, nautilus
bind = SUPER SHIFT,       S,         exec, steam
bind = SUPER,       V,         exec, copyq show
bind = SUPER, C, exec, zeditor
bind = SUPER SHIFT, C, exec, code
bind = SUPER SHIFT, V, exec, blueman-manager
#bind = SUPER SHIFT, A, exec, waypaper

#Oturum Menusu
bind = SUPER, X, exec, ~/.config/rofi/powermenu.sh


# Class görmek için kısayol
bind = SUPER SHIFT, Z, exec, notify-send "Aktif Pencere" "$(hyprctl activewindow | grep -E 'class:|title:' | sed 's/^[ \t]*//')"
