#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
monitor = eDP-1,    1920x1080@60, 1920x0, 1

input {
    kb_layout    = tr
    repeat_rate  = 35
    repeat_delay = 250
    numlock_by_default = true

    follow_mouse = 1
    mouse_refocus = false

    touchpad {
        tap-to-click         = true
        natural_scroll       = true
        disable_while_typing = false
    }

    sensitivity = -0.5
}

cursor {
    no_warps = true
}

# Trackpoint / libinput için ek ayarlar (isteğe bağlı):
# device {
#     name = <trackpoint-device-name>
#     sensitivity = 0.2
#     accel_profile = flat
#     scroll_method = on_button_down
#     scroll_button = 273
#     scroll_button_lock = true
#     middle_button_emulation = true
#     natural_scroll = true
# }
