windowrule {
    name = copyq_float
    match:class = com.github.hluk.copyq
    float = on
    size = 400 600
    center = on
}

windowrule {
    name = blueman_float
    match:class = blueman-manager
    float = on
    size = 600 600
    center = on
}

windowrule {
    name = zed_ws
    match:class = dev.zed.Zed
    workspace = 3
}

windowrule {
    name = Spotify_ws
    match:class = Spotify
    workspace = 2
}

windowrule {
    name = helium_ws
    match:class = helium
    workspace = 1
}

windowrule {
    name = obsidian
    match:class = obsidian
    workspace = 3
}

windowrule {
    name = zen_ws
    match:class = zen
    workspace = 1
}

windowrule {
    name = steam_ws
    match:class = steam
    workspace = 6
}
