windowrule {
    name = copyq_float
    match:class = com.github.hluk.copyq
    float = on
    size = 400 600
    center = on
}
windowrule {
    name = zed_ws
    match:class = dev.zed.Zed
    match:workspace = 4
}
windowrule {
    name = spotify_ws
    match:class = Spotify
    match:workspace = 2
}
windowrule {
    name = browser_ws
    match:class = helium
    match:workspace = 1
}
windowrule {
    name = note_ws
    match:class = obsidian
    match:workspace = 3
}
