exec-once = hyprctl setcursor PKP 24
exec-once = copyq
exec-once = xwayland-satellite
#exec-once = qs -c noctalia-shell
exec-once = hyprpaper
exec-once= waybar
exec-once= dunst
exec-once = gnome-keyring-daemon
exec-once = hyprsunset
